/**
 * Stub type definitions for Convex-generated API module.
 * These are generated by Convex when the component is integrated into a Convex project.
 * This file provides type stubs for compile-time type checking in isolation.
 */

export const api: any;
export const internal: any;
