/**
 * Stub type definitions for Convex-generated server module.
 * These are generated by Convex when the component is integrated into a Convex project.
 * This file provides type stubs for compile-time type checking in isolation.
 */

export const internalAction: any;
export const internalMutation: any;
export const internalQuery: any;
export const query: any;
export const mutation: any;
export const action: any;
export const httpAction: any;
export const httpRouter: any;
