/**
 * Ambient type definitions for Convex-generated modules.
 * These are generated by Convex when the component is integrated into a Convex project.
 * This file provides stubs for compile-time type checking in isolation.
 */

declare module './_generated/server' {
  export const internalAction: any;
  export const internalMutation: any;
  export const internalQuery: any;
  export const query: any;
  export const mutation: any;
  export const action: any;
  export const httpAction: any;
  export const httpRouter: any;
}

declare module './_generated/api' {
  export const api: any;
  export const internal: any;
}
